program mydate
        
contains

    subroutine usage (status)
        logical :: status

        if (status) then
            write (*, *) "Try 'mydate --help' for more information."
        else
            write (*, *) "Uso: mydate [OPÇÃO]... [+FORMATO]"
            write (*, *) " ou: mydate [-u|--utc|--universal] [MMDDhhmm[[CC]YY][.ss]]"
            write (*, *) "Display the current time in the given FORMAT, or set the system date."
            write (*, *) ""
            write (*, *) "Mandatory arguments to long options are mandatory for short options too."
            write (*, *) "  -d, --date=STRING         display time described by STRING, not 'now'"
            write (*, *) "  -f, --file=DATEFILE        like --date; once for each line of DATEFILE"
            write (*, *) "  -I[FMT], --iso-8601[=FMT]  output date/time in ISO 8601 format."
            write (*, *) "                               FMT='date' for date only (the default),"
            write (*, *) "                               'hours', 'minutes', 'seconds', or 'ns'"
            write (*, *) "                               for date and time to the indicated precision."
            write (*, *) "                               Example: 2006-08-14T02:34:56-0600"
            write (*, *) "  -R, --rfc-2822             output date and time in RFC 2822 format."
            write (*, *) "                               Example: Mon, 14 Aug 2006 02:34:56 -0600"
            write (*, *) "      --rfc-3339=FMT         output date/time in RFC 3339 format."
            write (*, *) "                               FMT='date', 'seconds', or 'ns'"
            write (*, *) "                               for date and time to the indicated precision."
            write (*, *) "                               Example: 2006-08-14 02:34:56-06:00"
            write (*, *) "  -r, --reference=FILE       display the last modification time of FILE"
            write (*, *) "  -s, --set=STRING           set time described by STRING"
            write (*, *) "  -u, --utc, --universal     print or set Coordinated Universal Time (UTC)"
            write (*, *) "      --help     mostra esta ajuda e finaliza"
            write (*, *) "      --version  informa a versão e finaliza"
            write (*, *) ""
            write (*, *) "FORMATO controla a saída. As sequências interpretadas são:"
            write (*, *) ""
            write (*, *) "  %%   um % literal"
            write (*, *) "  %a   nome abreviado do dia de semana da localidade (por exemplo, Sáb)"
            write (*, *) "  %A   nome completo do dia de semana na localidade (por exemplo, Sábado)"
            write (*, *) "  %b   nome abreviado do mês na localidade (por exemplo, Jan)"
            write (*, *) "  %B   nome completo do mês na localidade (por exemplo, Janeiro)"
            write (*, *) "  %c   data e hora na localidade (por exemplo, Sáb 08 Mar 2008 18:34:17 BRT)"
            write (*, *) "  %C   século; como %Y, mas omite os dois últimos dígitos (por exemplo, 21)"
            write (*, *) "  %d   dia do mês (por exemplo, 01)"
            write (*, *) "  %D   data no formato estado-unidense; o mesmo que %d/%m/%y"
            write (*, *) "  %e   dia do mês, preenchido com espaço; o mesmo que %_d"
            write (*, *) "  %F   data completa; o mesmo que %Y-%m-%d"
            write (*, *) "  %g   os últimos dois dígitos do ano do número ISO da semana (veja %G)"
            write (*, *) "  %G   ano do número ISO da semana ISO (veja %V); normalmente útil só com %V"
            write (*, *) "  %h   o mesmo que %b"
            write (*, *) "  %H   hora (00..23)"
            write (*, *) "  %I   hora (01..12)"
            write (*, *) "  %j   dia do ano (001..366)"
            write (*, *) "  %k   hora, com preenchimento de espaço ( 0..23); o mesmo que %_H"
            write (*, *) "  %l   hora, com preenchimento de espaço ( 1..12); o mesmo que %_I"
            write (*, *) "  %m   mês (01..12)"
            write (*, *) "  %M   minuto (00..59)"
            write (*, *) "  %n   um caractere de nova-linha"
            write (*, *) "  %N   nanosegundos (000000000..999999999)"
            write (*, *) "  %p   o equivalente na localidade para AM ou PM; em branco se desconhecido"
            write (*, *) "  %P   como %p, mas em minúsculas"
            write (*, *) "  %r   a hora no relógio de 12 horas na localidade (por exemplo, 11:11:04 PM)"
            write (*, *) "  %R   hora e minuto no estilo 24 horas; o mesmo que %H:%M"
            write (*, *) "  %s   segundos desde 1970-01-01 00:00:00 UTC"
            write (*, *) "  %S   segundo (00..60)"
            write (*, *) "  %t   uma tabulação"
            write (*, *) "  %T   as horas; o mesmo que %H:%M:%S"
            write (*, *) "  %u   dia da semana (1..7); 1 é segunda-feira"
            write (*, *) "  %U   número da semana no ano, sendo domingo o início da semana (00..53)"
            write (*, *) "  %V   número ISO da semana, sendo segunda-feira o início da semana (01..53)"
            write (*, *) "  %w   dia da semana (0..6); 0 é domingo"
            write (*, *) "  %W   número da semana no ano, sendo segunda-feira o início da semana (00..53)"
            write (*, *) "  %x   representação da data na localidade (por exemplo, 31/12/99)"
            write (*, *) "  %X   representação da hora na localidade (por exemplo, 23:13:48)"
            write (*, *) "  %y   os últimos dois dígitos do ano (00..99)"
            write (*, *) "  %Y   ano"
            write (*, *) "  %z   fuso horário numérico +hhmm (por exemplo, -0400)"
            write (*, *) "  %:z  fuso horário numérico +hh:mm (por exemplo, -04:00)"
            write (*, *) "  %::z  fuso horário numérico +hh:mm:ss (por exemplo, -04:00:00)"
            write (*, *) "  %:::z  fuso horário numérico com : para a precisão necessária"
            write (*, *) "           (por exemplo, -04, +05:30)"
            write (*, *) "  %Z   abreviação alfabética do fuso horário (por exemplo, BRT)"
            write (*, *) ""
            write (*, *) "Por padrão, campos numéricos de data são preenchidos com zeros."
            write (*, *) "As seguintes opções sinalizadoras podem seguir '%':"
            write (*, *) ""
            write (*, *) "  -  (hífen) não preencher o campo"
            write (*, *) "  _  (sublinhado) preencher com espaços"
            write (*, *) "  0  (zero) preencher com zeros"
            write (*, *) "  ^  usar letras maiúsculas, se possível"
            write (*, *) "  #  usar capitalização oposta, se possível"
            write (*, *) ""
            write (*, *) "Depois de qualquer sinalizador pode haver uma largura de campo opcional,"
            write (*, *) "como um número decimal; então, um modificador também opcional, que pode ser"
            write (*, *) " E para usar as representações alternativas da localidade, se disponível, ou"
            write (*, *) " O para usar os símbolos númericos alternativos da localidade, se disponível."
            write (*, *) ""
            write (*, *) "Exemplos:"
            write (*, *) "Converte segundos desde o período (1970-01-01 UTC) até uma data"
            write (*, *) "  $ mydate --date='@2147483647'"
            write (*, *) ""
            write (*, *) "Mostra a hora na costa oeste dos EUA (use tzselect(1) para encontrar TZ)"
            write (*, *) "  $ TZ='America/Los_Angeles' mydate"
            write (*, *) ""
            write (*, *) "Mostra a hora local para 9AM próxima sexta-feira na costa oeste dos EUA"
            write (*, *) "  $ mydate --date='TZ='America/Los_Angeles' 09:00 next Fri'"
            write (*, *) ""          
        end if

    end subroutine usage


end program mydate